[window]
opacity = 1
blur = true
padding = { x = 10, y = 10 }
dynamic_padding = true

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[colors.primary]
background = "#141414"
foreground = "#dfdfdf"

[colors.normal]
black   = "#141414"
red     = "#f44336"
green   = "#4caf50"
yellow  = "#ffeb3b"
blue    = "#2196f3"
magenta = "#9c27b0"
cyan    = "#00bcd4"
white   = "#dfdfdf"

[colors.bright]
black   = "#3c3c3c"
red     = "#ff5252"
green   = "#69f0ae"
yellow  = "#ffff00"
blue    = "#40c4ff"
magenta = "#e040fb"
cyan    = "#18ffff"
white   = "#ffffff"
