-- hshell / Hyprland Lua. Local hardware overrides are loaded at the end.
hl.config({ autogenerated = false })
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

hl.config({
    general = {
        gaps_in = 5, gaps_out = 5, border_size = 2,
        col = { active_border = "rgba(ffffffff)", inactive_border = "rgba(444444aa)" },
        resize_on_border = false, allow_tearing = true, layout = "dwindle",
    },
    decoration = {
        rounding = 0, active_opacity = 1.0, inactive_opacity = 1.0,
        dim_inactive = false, shadow = { enabled = false }, blur = { enabled = false },
    },
    animations = { enabled = false },
    render = { direct_scanout = false },
    dwindle = { preserve_split = true },
    master = { new_status = "master" },
    misc = { force_default_wallpaper = 0, disable_hyprland_logo = true, vrr = 0 },
    input = { kb_layout = "us", follow_mouse = 1, sensitivity = 0,
        accel_profile = "flat", touchpad = { natural_scroll = false } },
})

local mainMod = "SUPER"
local config = os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")
local function quote(value) return "'" .. value:gsub("'", "'\\''") .. "'" end
local function script(name) return "bash " .. quote(config .. "/scripts/" .. name) end
local function shell(panel) return "qs -c hshell ipc call hshell toggle " .. panel end
local function bind(key, command) hl.bind(mainMod .. " + " .. key, hl.dsp.exec_cmd(command)) end

hl.on("hyprland.start", function()
    hl.exec_cmd(script("session-start.sh"))
end)

bind("Return", "alacritty")
bind("space", shell("launcher"))
bind("X", "alacritty -e nvim")
bind("F", "thunar")
bind("B", script("browser.sh"))
bind("T", "signal-desktop")
bind("O", "obs")
bind("R", "resolve") -- Optional app: install separately if used.
bind("M", "audacious")
bind("P", "protonvpn-app")
bind("SHIFT + A", "pavucontrol")
bind("SHIFT + T", "alacritty -e btop")
bind("SHIFT + L", script("lock.sh"))
bind("Escape", shell("power"))
bind("SHIFT + space", shell("system"))
bind("CTRL + space", shell("tools"))
bind("N", shell("notifications"))
bind("CTRL + N", shell("notes"))
bind("SHIFT + M", shell("control"))
bind("SHIFT + D", "alacritty -e " .. script("tools.sh") .. " terminal downloader")
bind("G", shell("emoji"))
bind("C", shell("calendar"))
bind("SHIFT + B", shell("web"))
bind("SHIFT + W", shell("wallpaper"))
bind("SHIFT + V", shell("clipboard"))
bind("SHIFT + I", script("idle-toggle.sh"))
bind("SHIFT + P", script("shell-actions.sh") .. " power-profile-cycle")
bind("SHIFT + N", "qs -c hshell ipc call hshell dnd")
bind("SHIFT + U", "alacritty -e " .. script("tools.sh") .. " terminal update")
bind("SHIFT + C", "alacritty -e " .. script("tools.sh") .. " terminal clean")
-- Standalone screenshot keys requested in your newer config; no shell capture panel.
bind("SHIFT + S", script("screenshot.sh") .. " region")
bind("SHIFT + X", script("screenshot.sh") .. " full")
bind("SHIFT + H", "hyprpicker -a")

hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exit())
hl.bind(mainMod .. " + Z", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + W", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + Tab", hl.dsp.focus({ workspace = "previous" }))
hl.bind(mainMod .. " + D", hl.dsp.layout("togglesplit"))
for _, direction in ipairs({"left", "right", "up", "down"}) do
    hl.bind(mainMod .. " + " .. direction, hl.dsp.focus({ direction = direction }))
end
for i = 1, 9 do
    hl.bind(mainMod .. " + " .. i, hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +5%"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -5%"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

local overrides = config .. "/hypr/local.lua"
local file = io.open(overrides, "r")
if file then file:close(); dofile(overrides) end
