general {
    hide_cursor = true
}
background {
    monitor =
    path = $HOME/.local/state/hshell/wallpaper.png
    color = rgba(080808ff)
    blur_passes = 3
    blur_size = 7
    brightness = 0.65
}
label {
    monitor =
    text = cmd[update:60000] date '+%A, %B %-d'
    font_size = 22
    font_family = Inter
    color = rgba(ffffffff)
    position = 0, -100
    halign = center
    valign = top
}
label {
    monitor =
    text = $TIME
    font_size = 110
    font_family = Inter SemiBold
    color = rgba(ffffffff)
    position = 0, -140
    halign = center
    valign = top
}
label {
    monitor =
    text = 󰀄
    font_size = 32
    font_family = JetBrainsMono Nerd Font
    color = rgba(ffffffff)
    position = 0, 225
    halign = center
    valign = bottom
}
label {
    monitor =
    text = $USER
    font_size = 18
    font_family = Inter
    color = rgba(ffffffff)
    position = 0, 190
    halign = center
    valign = bottom
}
input-field {
    monitor =
    size = 240, 44
    position = 0, 120
    halign = center
    valign = bottom
    outline_thickness = 1
    outer_color = rgba(ffffff55)
    inner_color = rgba(202020bb)
    font_color = rgba(ffffffff)
    check_color = rgba(aaaaaaff)
    fail_color = rgba(777777ff)
    placeholder_text = Password
    rounding = 22
    dots_size = 0.2
    dots_spacing = 0.3
}
