general {
    hide_cursor = true
}
background {
    monitor =
    color = rgba(1e1e2eff)
    path = $HOME/.local/state/hshell/wallpaper.png
}
input-field {
    monitor =
    size = 280, 52
    position = 0, -80
    halign = center
    valign = center
    outline_thickness = 2
    outer_color = rgba(89b4faff)
    inner_color = rgba(000000ff)
    font_color = rgba(cdd6f4ff)
    check_color = rgba(aaaaaaff)
    fail_color = rgba(777777ff)
    placeholder_text = Password
    rounding = 12
}
label {
    monitor =
    text = $TIME
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    color = rgba(cdd6f4ff)
    position = 0, 70
    halign = center
    valign = center
}
