hl.config({ autogenerated = false })

hl.monitor({
	output = "DP-3",
	mode = "1920x1080@280",
	position = "1080x1080",
	scale = 1,
	transform = 0,
})

hl.monitor({
	output = "HDMI-A-1",
	mode = "1920x1080@60",
	position = "1080x0",
	scale = 1,
	transform = 0,
})

hl.monitor({
	output = "DP-1",
	mode = "1920x1080@180",
	position = "0x240",
	scale = 1,
	transform = 1,
})

hl.monitor({
	output = "DP-2",
	mode = "1920x1080@180",
	position = "3000x240",
	scale = 1,
	transform = 3,
})

hl.workspace_rule({ workspace = "1", monitor = "DP-3", default = true })
hl.workspace_rule({ workspace = "2", monitor = "HDMI-A-1", default = true })
hl.workspace_rule({ workspace = "3", monitor = "DP-1", default = true })
hl.workspace_rule({ workspace = "4", monitor = "DP-2", default = true })

hl.env("TERMINAL", "alacritty")
hl.env("EDITOR", "nvim")
hl.env("VISUAL", "nvim")
hl.env("BROWSER", "helium-browser")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.config({
	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		col = { active_border = "rgba(FFFFFFFF)", inactive_border = "rgba(808080FF)" },
		resize_on_border = false,
		allow_tearing = false,
		layout = "dwindle",
	},
	decoration = {
		rounding = 0,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		dim_inactive = false,
		shadow = { enabled = false },
		blur = { enabled = false },
	},
	animations = { enabled = true },
	render = { direct_scanout = false },
	dwindle = { preserve_split = true },
	master = { new_status = "master" },
	misc = { force_default_wallpaper = 0, disable_hyprland_logo = true, vrr = 0 },
	input = {
		kb_layout = "lv",
		follow_mouse = 1,
		sensitivity = 0,
		accel_profile = "flat",
		touchpad = { natural_scroll = false },
	},
})

hl.curve("hshell", { type = "bezier", points = { { 0.16, 1 }, { 0.3, 1 } } })
hl.animation({ leaf = "windows", enabled = true, speed = 5, bezier = "hshell", style = "popin" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "hshell", style = "slide" })
hl.animation({ leaf = "fade", enabled = false })
hl.animation({ leaf = "layers", enabled = false })

local mainMod = "SUPER"
local config = os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")
local function quote(value)
	return "'" .. value:gsub("'", "'\\''") .. "'"
end
local function script(name)
	return "bash " .. quote(config .. "/scripts/" .. name)
end
local function shell(panel)
	return "qs -c hshell ipc call hshell toggle " .. panel
end
local function bind(key, command)
	hl.bind(mainMod .. " + " .. key, hl.dsp.exec_cmd(command))
end

hl.on("hyprland.start", function()
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("python3 " .. quote(config .. "/scripts/wallpaper.py") .. " restore-wallpaper")
	hl.exec_cmd("hypridle")
	hl.exec_cmd(script("start-hshell.sh"))
end)

bind("Return", "alacritty")
bind("space", shell("launcher"))
bind("X", "alacritty -e nvim")
bind("F", "python3 " .. quote(config .. "/scripts/open-default.py") .. " files")
bind("B", "python3 " .. quote(config .. "/scripts/open-default.py") .. " browser")
bind("SHIFT + L", script("lock.sh"))
bind("Escape", shell("power"))
bind("SHIFT + space", shell("menu"))
bind("SHIFT + M", shell("control"))
bind("SHIFT + D", "qs -c hshell ipc call hshell tool download")
bind("C", shell("calendar"))
bind("SHIFT + V", shell("clipboard"))
bind("SHIFT + U", "alacritty -e " .. script("tools.sh") .. " terminal update")
bind("SHIFT + C", "alacritty -e " .. script("tools.sh") .. " terminal clean")
bind("SHIFT + E", script("screen-search.sh"))
bind("SHIFT + S", script("screenshot.sh") .. " region")
bind("SHIFT + X", script("screenshot.sh") .. " full")
bind("SHIFT + B", shell("web"))

hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exit())
hl.bind(mainMod .. " + Z", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + W", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + D", hl.dsp.layout("togglesplit"))
for _, direction in ipairs({ "left", "right", "up", "down" }) do
	hl.bind(mainMod .. " + " .. direction, hl.dsp.focus({ direction = direction }))
end
for i = 1, 9 do
	hl.bind(mainMod .. " + " .. i, hl.dsp.focus({ workspace = i }))
	hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +5%; qs -c hshell ipc call hshell osd volume"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -5%; qs -c hshell ipc call hshell osd volume"),
	{ locked = true, repeating = true }
)
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"), { locked = true })
hl.bind(
	"XF86MonBrightnessUp",
	hl.dsp.exec_cmd("brightnessctl set 5%+; qs -c hshell ipc call hshell osd brightness"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86MonBrightnessDown",
	hl.dsp.exec_cmd("brightnessctl set 5%-; qs -c hshell ipc call hshell osd brightness"),
	{ locked = true, repeating = true }
)
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--# Zoom
local function zoomfunction(value)
	local zoomvalue = hl.get_config("cursor:zoom_factor")
	if (zoomvalue + value) > 3.0 then
		hl.config({ cursor = { zoom_factor = 3.0 } })
	elseif (zoomvalue + value) < 1.0 then
		hl.config({ cursor = { zoom_factor = 1.0 } })
	else
		hl.config({ cursor = { zoom_factor = zoomvalue + value } })
	end
end
hl.bind("SUPER + Minus", function()
	zoomfunction(-0.3)
end, { repeating = true, description = "Screen: Zoom out" })
hl.bind("SUPER + Equal", function()
	zoomfunction(0.3)
end, { repeating = true, description = "Screen: Zoom in" })

--# Zoom with keypad
hl.bind("SUPER + code:82", function()
	zoomfunction(-0.3)
end, { repeating = true })
hl.bind("SUPER + code:86", function()
	zoomfunction(0.3)
end, { repeating = true })
bind("P", "protonvpn-app")
bind("O", "obs")
bind("R", "resolve")
