general {
    lock_cmd = sh -c 'exec "${XDG_CONFIG_HOME:-$HOME/.config}/scripts/lock.sh"'
    before_sleep_cmd = loginctl lock-session
    inhibit_sleep = 3
}
listener {
    timeout = 600
    on-timeout = sh -c 'exec "${XDG_CONFIG_HOME:-$HOME/.config}/scripts/idle-action.sh" lock'
}
listener {
    timeout = 1800
    on-timeout = sh -c 'exec "${XDG_CONFIG_HOME:-$HOME/.config}/scripts/idle-action.sh" suspend'
}
