-- hshell: portable defaults. Edit monitor/keyboard settings here for your machine.
hl.config({ autogenerated = false })
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })
hl.env("TERMINAL", "alacritty")
hl.env("EDITOR", "nvim")
hl.env("VISUAL", "nvim")
hl.env("BROWSER", "librewolf")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

hl.config({
    general = {
        gaps_in = 5, gaps_out = 5, border_size = 2,
        col = { active_border = "rgba(89b4faff)", inactive_border = "rgba(45475aff)" },
        resize_on_border = false, allow_tearing = false, layout = "dwindle",
    },
    decoration = {
        rounding = 0, active_opacity = 1.0, inactive_opacity = 1.0,
        dim_inactive = false, shadow = { enabled = false }, blur = { enabled = false },
    },
    animations = { enabled = false },
    render = { direct_scanout = false },
    dwindle = { preserve_split = true },
    master = { new_status = "master" },
    misc = { force_default_wallpaper = 0, disable_hyprland_logo = true, vrr = 0 },
    input = { kb_layout = "us", follow_mouse = 1, sensitivity = 0,
        accel_profile = "flat", touchpad = { natural_scroll = false } },
})

local mainMod = "SUPER"
local config = os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")
local function quote(value) return "'" .. value:gsub("'", "'\\''") .. "'" end
local function script(name) return "bash " .. quote(config .. "/scripts/" .. name) end
local function shell(panel) return "qs -c hshell ipc call hshell toggle " .. panel end
local function bind(key, command) hl.bind(mainMod .. " + " .. key, hl.dsp.exec_cmd(command)) end

hl.on("hyprland.start", function()
    -- All session startup commands are listed here. No X11 .xprofile is used.
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("python3 " .. quote(config .. "/scripts/wallpaper.py") .. " restore-wallpaper")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("hypridle")
    -- hshell includes the notification server and the Polkit authentication agent.
    hl.exec_cmd("qs -c hshell")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets,pkcs11")
end)

bind("Return", "alacritty")
bind("space", shell("launcher"))
bind("X", "alacritty -e nvim")
bind("F", "thunar")
bind("B", "librewolf")
bind("SHIFT + L", script("lock.sh"))
bind("Escape", shell("power"))
bind("SHIFT + space", shell("system"))
bind("CTRL + space", shell("tools"))
bind("N", shell("notifications"))
bind("SHIFT + M", shell("control"))
bind("SHIFT + D", "qs -c hshell ipc call hshell tool download")
bind("G", "qs -c hshell ipc call hshell tool emoji")
bind("C", shell("calendar"))
bind("SHIFT + W", shell("wallpaper"))
bind("SHIFT + V", shell("clipboard"))
bind("SHIFT + I", "qs -c hshell ipc call hshell caffeine")
bind("SHIFT + P", script("shell-actions.sh") .. " power-profile-cycle")
bind("SHIFT + N", "qs -c hshell ipc call hshell dnd")
bind("SHIFT + U", "alacritty -e " .. script("tools.sh") .. " terminal update")
bind("SHIFT + C", "alacritty -e " .. script("tools.sh") .. " terminal clean")
bind("Prior", shell("overview")) -- Super + PageUp
bind("SHIFT + E", script("screen-search.sh"))
-- Standalone screenshots, no capture panel.
bind("SHIFT + S", script("screenshot.sh") .. " region")
bind("SHIFT + X", script("screenshot.sh") .. " full")
bind("SHIFT + H", "hyprpicker -a")

hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exit())
hl.bind(mainMod .. " + Z", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + W", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + Tab", hl.dsp.focus({ workspace = "previous" }))
hl.bind(mainMod .. " + D", hl.dsp.layout("togglesplit"))
for _, direction in ipairs({"left", "right", "up", "down"}) do
    hl.bind(mainMod .. " + " .. direction, hl.dsp.focus({ direction = direction }))
end
for i = 1, 9 do
    hl.bind(mainMod .. " + " .. i, hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +5%; qs -c hshell ipc call hshell osd volume"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -5%; qs -c hshell ipc call hshell osd volume"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+; qs -c hshell ipc call hshell osd brightness"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-; qs -c hshell ipc call hshell osd brightness"), { locked = true, repeating = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
